export const competitorsContent = {
  title: "Competitor Analysis",
  subtitle: "Where the market leaders fall short — and where Ascent wins",
  intro: "Understanding what Royal Mail and Detrack do well is just half the picture. The real strategic insight is in the gaps — the capabilities they've either deprioritised, failed to build, or are structurally unable to deliver. Those gaps are Ascent's opportunity.",

  gapFraming: {
    title: "The Gap Analysis Framework",
    description: "We evaluated both competitors across six dimensions critical to modern parcel tracking. Green indicates a strong capability; amber a partial or inconsistent one; red a genuine weakness or absence.",
    dimensions: ["Live GPS Tracking", "Parcel-Level Visibility", "Automated Exceptions", "Customer Experience", "SME Accessibility", "Innovation Velocity"],
  },

  competitors: [
    {
      id: "royal-mail",
      name: "Royal Mail",
      type: "Incumbent Carrier",
      logo: "📮",
      founded: "1516",
      scale: "15M+ deliveries/day",
      color: "#ef4444",
      tagline: "Scale without sophistication",
      overview: "Royal Mail is the UK's largest postal operator — a 500-year-old institution processing over 15 million items daily. Its tracking infrastructure is extensive but fundamentally checkpoint-based, built on legacy systems that prioritise volume over visibility.",
      strengths: [
        { point: "Unmatched national coverage", detail: "Every UK postcode, six days a week" },
        { point: "Brand trust at consumer level", detail: "Highest recognition and baseline confidence of any UK carrier" },
        { point: "Infrastructure investment ongoing", detail: "Multi-year programme to modernise depot operations" },
        { point: "Integrated returns network", detail: "1,200+ Post Office locations as drop-off/collection points" },
      ],
      weaknesses: [
        { point: "No live GPS parcel tracking", detail: "Checkpoint scanning only — no real-time location between scan events", severity: "critical" },
        { point: "Poor exception communication", detail: "Automated notifications are delayed and generic", severity: "high" },
        { point: "Legacy technology debt", detail: "Core systems are decades old; modernisation is slow and expensive", severity: "high" },
        { point: "Limited SME tooling", detail: "Business APIs are complex and poorly documented for smaller shippers", severity: "medium" },
        { point: "No condition monitoring", detail: "Zero capability for fragile/temperature-sensitive parcel tracking", severity: "medium" },
      ],
      scores: {
        "Live GPS Tracking": 1,
        "Parcel-Level Visibility": 2,
        "Automated Exceptions": 2,
        "Customer Experience": 3,
        "SME Accessibility": 2,
        "Innovation Velocity": 2,
      },
      verdict: "Royal Mail's scale is its moat — but also its anchor. The same infrastructure that delivers 15 million items daily is what prevents rapid modernisation. For Ascent, this creates a clear opportunity to offer enterprise-grade tracking to the SME segment that Royal Mail consistently underserves.",
      opportunity: "SME tracking gap + parcel-level GPS + proactive exception management",
    },
    {
      id: "detrack",
      name: "Detrack",
      type: "SaaS Tracking Platform",
      logo: "🚚",
      founded: "2014",
      scale: "Global SaaS, 60+ countries",
      color: "#3b82f6",
      tagline: "Strong features, shallow roots",
      overview: "Detrack is a cloud-based last-mile delivery management platform with a strong mobile app for drivers and a solid proof-of-delivery feature set. It's a genuinely capable product — but one built for generic logistics rather than UK-specific parcel operations.",
      strengths: [
        { point: "Excellent mobile driver app", detail: "Clean UX, offline capability, fast photo capture" },
        { point: "Solid proof of delivery", detail: "Photo, signature, and geolocation evidence on delivery" },
        { point: "Easy onboarding for SMEs", detail: "Self-service setup with transparent pricing" },
        { point: "API-first architecture", detail: "Clean REST API with good documentation" },
        { point: "Real-time driver tracking", detail: "Vehicle-level GPS visible to dispatch" },
      ],
      weaknesses: [
        { point: "No parcel-level tracking hardware", detail: "Relies entirely on driver-app GPS — parcel tracking stops when driver logs off", severity: "critical" },
        { point: "Generic platform, no UK specificity", detail: "No Royal Mail integration, no UK customs workflows, no IOSS handling", severity: "high" },
        { point: "No depot-to-door continuity", detail: "Tracking coverage begins when the driver starts a route, not when parcel enters the network", severity: "high" },
        { point: "Limited analytics depth", detail: "Basic performance dashboards — no trend analysis or benchmarking", severity: "medium" },
        { point: "No condition/tamper monitoring", detail: "Zero support for fragile or high-value parcel condition tracking", severity: "medium" },
      ],
      scores: {
        "Live GPS Tracking": 3,
        "Parcel-Level Visibility": 2,
        "Automated Exceptions": 3,
        "Customer Experience": 4,
        "SME Accessibility": 5,
        "Innovation Velocity": 4,
      },
      verdict: "Detrack proves there's strong demand for accessible, app-driven delivery management. But its reliance on driver-app GPS means tracking coverage has fundamental gaps — and its generic positioning means it will never be optimised for the UK parcel market specifically. Ascent can take the best of Detrack's UX philosophy and combine it with genuine parcel-level hardware tracking.",
      opportunity: "UK-specific platform + hardware-backed parcel tracking + depot-to-door continuity",
    },
    {
      id: "evri",
      name: "Evri",
      type: "UK Courier / Parcel Delivery",
      logo: "🟣",
      founded: "2022 (rebranded from Hermes)",
      scale: "~800M parcels/year (2025 projection)",
      color: "#a855f7",
      tagline: "Delivering for the UK's biggest e-commerce brands",
      overview: "Evri is one of the UK's largest parcel carriers, serving major e-commerce brands and marketplaces. Rebranded from Hermes in 2022 following sustained reputational damage, Evri has invested heavily in infrastructure and technology — but its structural reliance on a self-employed courier model continues to create systemic reliability challenges.",
      strengths: [
        { point: "Large delivery network", detail: "Tens of thousands of couriers and thousands of parcel shops and lockers across the UK" },
        { point: "Low-cost delivery", detail: "Widely used by retailers to reduce shipping costs at scale" },
        { point: "Strong e-commerce presence", detail: "Partners with major marketplaces and retailers, including significant Amazon volume" },
        { point: "Investment in technology", detail: "Automated sorting hubs, tracking tech, and real-time delivery updates" },
        { point: "High delivery success in trials", detail: "~97% next-day delivery success rate achieved with Amazon pilot programmes" },
      ],
      weaknesses: [
        { point: "Poor customer service", detail: "Significant difficulty contacting a real person when parcels are missing or damaged", severity: "critical" },
        { point: "Parcel handling issues", detail: "Persistent reports of lost, damaged, and mishandled parcels across consumer review platforms", severity: "critical" },
        { point: "Self-employed courier model", detail: "Inconsistent service quality resulting from contractor-based workforce without direct quality controls", severity: "high" },
        { point: "High courier workloads", detail: "Large daily delivery volumes per courier affect performance and care standards", severity: "medium" },
        { point: "Reputational legacy", detail: "Rebranded from Hermes due to severe negative publicity; trust challenges persist despite investment", severity: "high" },
      ],
      scores: {
        "Live GPS Tracking": 3,
        "Parcel-Level Visibility": 2,
        "Automated Exceptions": 2,
        "Customer Experience": 2,
        "SME Accessibility": 3,
        "Innovation Velocity": 3,
      },
      verdict: "Evri's scale is impressive but its service quality problems are structural. The reliance on self-employed couriers and a volume-first growth strategy creates systemic reliability issues that technology investment alone hasn't fixed. The rebrand addressed the name; the underlying model remains unchanged.",
      opportunity: "Real-time GPS tracking and automated anomaly detection would directly address the parcel loss and customer service failure modes that define Evri's biggest weaknesses.",
    },
    {
      id: "dpd",
      name: "DPD",
      type: "Express Parcel Carrier",
      logo: "🔴",
      founded: "1977",
      scale: "400M+ parcels/year (UK)",
      color: "#dc2626",
      tagline: "Precise. Predictive. Premium.",
      overview: "DPD UK is widely regarded as the market leader in tracking-forward parcel delivery, having pioneered the one-hour delivery window and live driver tracking. Part of the GeoPost/DPDgroup network, DPD has built its brand around predictability and communication — but its pricing model increasingly excludes smaller retailers.",
      strengths: [
        { point: "Industry-leading tracking UX", detail: "One-hour delivery windows, live driver map, and proactive SMS/email notifications" },
        { point: "Strong reliability record", detail: "Consistently high first-attempt delivery success rates versus industry average" },
        { point: "Extensive UK network", detail: "Over 90 UK depots and a dense nationwide collection/delivery infrastructure" },
        { point: "Sustainable fleet investment", detail: "Significant EV fleet rollout, electric micro-depots in city centres" },
        { point: "Robust API and integrations", detail: "Well-documented developer tools and pre-built e-commerce platform connectors" },
      ],
      weaknesses: [
        { point: "Premium pricing excludes SMEs", detail: "Cost structure is optimised for high-volume enterprise contracts — SMEs face significantly higher per-parcel rates", severity: "high" },
        { point: "No parcel-level hardware tracking", detail: "Tracking remains vehicle and checkpoint-based — no parcel-attached sensor data", severity: "high" },
        { point: "Limited condition monitoring", detail: "No temperature, shock, or tamper detection for fragile or high-value items", severity: "medium" },
        { point: "Depot congestion issues", detail: "High volume periods (peak season) see service degradation at major sorting hubs", severity: "medium" },
        { point: "Reactive exception management", detail: "Automated alerts are good but exception resolution still requires manual intervention", severity: "medium" },
      ],
      scores: {
        "Live GPS Tracking": 4,
        "Parcel-Level Visibility": 3,
        "Automated Exceptions": 4,
        "Customer Experience": 5,
        "SME Accessibility": 2,
        "Innovation Velocity": 4,
      },
      verdict: "DPD sets the current benchmark for tracking-forward delivery in the UK. Its consumer-facing experience is genuinely excellent. But it is built for enterprise scale, priced accordingly, and offers no parcel-level sensor capability. For SMEs and shippers of high-value goods, the gap between what DPD promises and what it can technically deliver remains significant.",
      opportunity: "SME-accessible pricing + parcel-level GPS hardware + condition monitoring for fragile/high-value shipments.",
    },
    {
      id: "amazon-logistics",
      name: "Amazon Logistics",
      type: "Captive Carrier / Last-Mile Network",
      logo: "📦",
      founded: "2015",
      scale: "3B+ parcels/year (UK & global estimate)",
      color: "#f59e0b",
      tagline: "Built for Amazon. Used for everything else.",
      overview: "Amazon Logistics (AMZL) was built to reduce Amazon's dependence on third-party carriers and now handles the majority of Amazon's own UK deliveries. It is the most technologically sophisticated last-mile operation in the market — but it exists primarily to serve Amazon's own commercial interests, with third-party carrier services remaining secondary and access-restricted.",
      strengths: [
        { point: "Unmatched technology investment", detail: "Proprietary routing algorithms, predictive delivery windows, drone and autonomous vehicle R&D" },
        { point: "Dense urban delivery coverage", detail: "Extremely high delivery density in major UK cities, enabling sub-24-hour economics" },
        { point: "Deep data integration", detail: "End-to-end visibility from order placement through to doorstep delivery with photo confirmation" },
        { point: "Scale-driven cost efficiency", detail: "Volume allows per-parcel costs that no independent carrier can match" },
        { point: "Amazon Flex model", detail: "Flexible workforce scaling via gig-economy drivers matched to demand fluctuations" },
      ],
      weaknesses: [
        { point: "Closed ecosystem — not a public carrier", detail: "AMZL primarily serves Amazon's own marketplace; third-party access is limited and strategically restricted", severity: "critical" },
        { point: "Conflict of interest for competing retailers", detail: "Retailers who compete with Amazon Marketplace are directly funding a competitor's logistics advantage", severity: "critical" },
        { point: "Inconsistent rural coverage", detail: "Network density drops sharply outside major urban areas — rural deliveries often handed to Royal Mail", severity: "high" },
        { point: "Gig workforce reliability variance", detail: "Amazon Flex driver quality and accountability varies significantly — no consistent employment standard", severity: "medium" },
        { point: "Black box operations", detail: "Minimal transparency into AMZL's operational processes or data for external partners", severity: "medium" },
      ],
      scores: {
        "Live GPS Tracking": 5,
        "Parcel-Level Visibility": 4,
        "Automated Exceptions": 5,
        "Customer Experience": 4,
        "SME Accessibility": 1,
        "Innovation Velocity": 5,
      },
      verdict: "Amazon Logistics is the most capable last-mile operation in the UK — but it is not a public carrier. Its technology advantage is real but entirely captive to Amazon's own commercial agenda. Any retailer relying on AMZL is subsidising a competitor's logistics infrastructure. For the broader market, AMZL sets the technology benchmark while simultaneously being inaccessible to the businesses who need it most.",
      opportunity: "Independent, SME-accessible platform with comparable tracking sophistication — without the conflict of interest of routing shipments through a competitor's infrastructure.",
    },
  ],

  ascentPosition: {
    title: "Where Ascent Wins",
    description: "The combined gap analysis reveals a clear white space: no competitor currently offers parcel-level GPS tracking with UK-specific workflows, SME-accessible pricing, and full depot-to-door visibility.",
    advantages: [
      { advantage: "Hardware + Software Integration", detail: "Magnetic GPS tags + platform = tracking that doesn't rely on drivers or depots" },
      { advantage: "UK-First Design", detail: "Built for UK customs, Royal Mail integrations, and British consumer expectations" },
      { advantage: "Full Journey Visibility", detail: "Depot intake → transit → delivery → return — no black boxes" },
      { advantage: "SME-Accessible Pricing", detail: "Scalable model that serves 50-parcel/day operations, not just enterprise contracts" },
    ],
  },
};
