export const competitorsContent = {
  title: "Competitor Analysis",
  subtitle: "Where the market leaders fall short — and where Ascent wins",
  intro: "Understanding what Royal Mail and Detrack do well is just half the picture. The real strategic insight is in the gaps — the capabilities they've either deprioritised, failed to build, or are structurally unable to deliver. Those gaps are Ascent's opportunity.",

  gapFraming: {
    title: "The Gap Analysis Framework",
    description: "We evaluated both competitors across six dimensions critical to modern parcel tracking. Green indicates a strong capability; amber a partial or inconsistent one; red a genuine weakness or absence.",
    dimensions: ["Live GPS Tracking", "Parcel-Level Visibility", "Automated Exceptions", "Customer Experience", "SME Accessibility", "Innovation Velocity"],
  },

  competitors: [
    {
      id: "royal-mail",
      name: "Royal Mail",
      type: "Incumbent Carrier",
      logo: "📮",
      founded: "1516",
      scale: "15M+ deliveries/day",
      color: "#ef4444",
      tagline: "Scale without sophistication",
      overview: "Royal Mail is the UK's largest postal operator — a 500-year-old institution processing over 15 million items daily. Its tracking infrastructure is extensive but fundamentally checkpoint-based, built on legacy systems that prioritise volume over visibility.",
      strengths: [
        { point: "Unmatched national coverage", detail: "Every UK postcode, six days a week" },
        { point: "Brand trust at consumer level", detail: "Highest recognition and baseline confidence of any UK carrier" },
        { point: "Infrastructure investment ongoing", detail: "Multi-year programme to modernise depot operations" },
        { point: "Integrated returns network", detail: "1,200+ Post Office locations as drop-off/collection points" },
      ],
      weaknesses: [
        { point: "No live GPS parcel tracking", detail: "Checkpoint scanning only — no real-time location between scan events", severity: "critical" },
        { point: "Poor exception communication", detail: "Automated notifications are delayed and generic", severity: "high" },
        { point: "Legacy technology debt", detail: "Core systems are decades old; modernisation is slow and expensive", severity: "high" },
        { point: "Limited SME tooling", detail: "Business APIs are complex and poorly documented for smaller shippers", severity: "medium" },
        { point: "No condition monitoring", detail: "Zero capability for fragile/temperature-sensitive parcel tracking", severity: "medium" },
      ],
      scores: {
        "Live GPS Tracking": 1,
        "Parcel-Level Visibility": 2,
        "Automated Exceptions": 2,
        "Customer Experience": 3,
        "SME Accessibility": 2,
        "Innovation Velocity": 2,
      },
      verdict: "Royal Mail's scale is its moat — but also its anchor. The same infrastructure that delivers 15 million items daily is what prevents rapid modernisation. For Ascent, this creates a clear opportunity to offer enterprise-grade tracking to the SME segment that Royal Mail consistently underserves.",
      opportunity: "SME tracking gap + parcel-level GPS + proactive exception management",
    },
    {
      id: "detrack",
      name: "Detrack",
      type: "SaaS Tracking Platform",
      logo: "🚚",
      founded: "2014",
      scale: "Global SaaS, 60+ countries",
      color: "#3b82f6",
      tagline: "Strong features, shallow roots",
      overview: "Detrack is a cloud-based last-mile delivery management platform with a strong mobile app for drivers and a solid proof-of-delivery feature set. It's a genuinely capable product — but one built for generic logistics rather than UK-specific parcel operations.",
      strengths: [
        { point: "Excellent mobile driver app", detail: "Clean UX, offline capability, fast photo capture" },
        { point: "Solid proof of delivery", detail: "Photo, signature, and geolocation evidence on delivery" },
        { point: "Easy onboarding for SMEs", detail: "Self-service setup with transparent pricing" },
        { point: "API-first architecture", detail: "Clean REST API with good documentation" },
        { point: "Real-time driver tracking", detail: "Vehicle-level GPS visible to dispatch" },
      ],
      weaknesses: [
        { point: "No parcel-level tracking hardware", detail: "Relies entirely on driver-app GPS — parcel tracking stops when driver logs off", severity: "critical" },
        { point: "Generic platform, no UK specificity", detail: "No Royal Mail integration, no UK customs workflows, no IOSS handling", severity: "high" },
        { point: "No depot-to-door continuity", detail: "Tracking coverage begins when the driver starts a route, not when parcel enters the network", severity: "high" },
        { point: "Limited analytics depth", detail: "Basic performance dashboards — no trend analysis or benchmarking", severity: "medium" },
        { point: "No condition/tamper monitoring", detail: "Zero support for fragile or high-value parcel condition tracking", severity: "medium" },
      ],
      scores: {
        "Live GPS Tracking": 3,
        "Parcel-Level Visibility": 2,
        "Automated Exceptions": 3,
        "Customer Experience": 4,
        "SME Accessibility": 5,
        "Innovation Velocity": 4,
      },
      verdict: "Detrack proves there's strong demand for accessible, app-driven delivery management. But its reliance on driver-app GPS means tracking coverage has fundamental gaps — and its generic positioning means it will never be optimised for the UK parcel market specifically. Ascent can take the best of Detrack's UX philosophy and combine it with genuine parcel-level hardware tracking.",
      opportunity: "UK-specific platform + hardware-backed parcel tracking + depot-to-door continuity",
    },
  ],

  ascentPosition: {
    title: "Where Ascent Wins",
    description: "The combined gap analysis reveals a clear white space: no competitor currently offers parcel-level GPS tracking with UK-specific workflows, SME-accessible pricing, and full depot-to-door visibility.",
    advantages: [
      { advantage: "Hardware + Software Integration", detail: "Magnetic GPS tags + platform = tracking that doesn't rely on drivers or depots" },
      { advantage: "UK-First Design", detail: "Built for UK customs, Royal Mail integrations, and British consumer expectations" },
      { advantage: "Full Journey Visibility", detail: "Depot intake → transit → delivery → return — no black boxes" },
      { advantage: "SME-Accessible Pricing", detail: "Scalable model that serves 50-parcel/day operations, not just enterprise contracts" },
    ],
  },
};
