export const recommendationsContent = {
  title: "Strategic Recommendations",
  subtitle: "Three paths forward. One clear winner.",
  intro: "The evidence from the market, technology, and competitor analysis points to a clear strategic direction. These three recommendations are presented in priority order — with the first representing Ascent's highest-value, lowest-risk opportunity for immediate competitive differentiation.",

  verdict: {
    headline: "The Strategic Verdict",
    body: "Ascent should lead with Magnetic GPS Tags as the core differentiator — it requires no infrastructure overhaul, delivers immediate parcel-level tracking, and occupies a capability gap that neither Royal Mail nor Detrack currently fills. The Automated System amplifies this advantage at scale. The Hybrid Approach is the long-term vision.",
  },

  recommendations: [
    {
      id: "magnetic-gps",
      rank: 1,
      badge: "Recommended",
      badgeColor: "green",
      title: "Magnetic GPS Parcel Tracking",
      subtitle: "The fastest path to genuine differentiation",
      icon: "🧲",
      color: "#22c55e",
      description: "Deploy magnetic GPS tags on high-value and tracked parcels, providing real-time location data via cellular networks — no vehicle modification required. This immediately closes the biggest gap in the market: the absence of live, parcel-level tracking.",
      strategic_rationale: "Magnetic GPS is the only technology that delivers live parcel-level tracking without requiring infrastructure investment or carrier cooperation. It's retrofit-ready, scalable from day one, and directly addresses the consumer's top demand: knowing exactly where their parcel is, right now.",
      pros: [
        "No infrastructure required — attach and track immediately",
        "Works on any carrier or vehicle type",
        "Real-time consumer-facing tracking maps",
        "Directly reduces theft and misdelivery disputes",
        "Scales from 1 to 1 million parcels without system changes",
      ],
      cons: [
        "Per-unit cost needs to be absorbed or passed on",
        "Battery lifecycle management required at scale",
        "Cellular data costs as ongoing OPEX",
      ],
      timeframe: "0–6 months",
      investment: "Medium",
      impact: "Very High",
      risk: "Low",
      kpis: [
        "Theft incidents per 1,000 deliveries",
        "Customer satisfaction score (tracking-related)",
        "Dispute resolution time",
        "Consumer tracking engagement rate",
      ],
    },
    {
      id: "automated-system",
      rank: 2,
      badge: "Conditional",
      badgeColor: "blue",
      title: "Automated Tracking & Exception System",
      subtitle: "Intelligence at scale — once the foundation is built",
      icon: "⚙️",
      color: "#3b82f6",
      description: "Build an automated exception management platform that detects delays, misrouting, and delivery failures in real-time, triggering proactive customer and retailer notifications before a complaint is raised.",
      strategic_rationale: "The data shows that 68% of consumers experienced delivery issues — but most only find out when the parcel doesn't arrive. An automated exception system transforms reactive customer service into proactive communication, dramatically improving satisfaction scores with minimal incremental cost once the tracking infrastructure is in place.",
      pros: [
        "Transforms customer service from reactive to proactive",
        "Reduces inbound complaint volume by 40–60% (industry benchmark)",
        "Provides retailers with real-time operational intelligence",
        "Enables SLA-based performance contracts with automatic compensation triggers",
        "Creates a data moat — insights competitors can't access",
      ],
      cons: [
        "Requires GPS/IoT tracking infrastructure as prerequisite",
        "Platform integration complexity with retailer systems",
        "Requires customer communication strategy and templates",
      ],
      timeframe: "6–18 months",
      investment: "High",
      impact: "High",
      risk: "Medium",
      kpis: [
        "Proactive notification rate (target: >90% of exceptions)",
        "Inbound complaint reduction percentage",
        "Retailer NPS score",
        "SLA breach rate",
      ],
    },
    {
      id: "hybrid",
      rank: 3,
      badge: "Supplementary",
      badgeColor: "purple",
      title: "Hybrid Tracking Architecture",
      subtitle: "The long-term vision — technology working in concert",
      icon: "🔗",
      color: "#a78bfa",
      description: "Combine GPS, RFID, IoT sensors, and computer vision into a unified tracking platform that provides continuous, multi-source location and condition data from depot intake to doorstep delivery.",
      strategic_rationale: "No single technology solves every tracking challenge. GPS excels in transit but struggles indoors. RFID is perfect for depot bulk scanning but has no range outdoors. Computer vision automates damage detection but is depot-bound. A hybrid architecture plays each technology to its strengths across the full parcel journey.",
      pros: [
        "Eliminates all tracking blind spots — full depot-to-door continuity",
        "Each technology reinforces the others' weaknesses",
        "Condition monitoring for high-value and fragile goods",
        "Maximum automation — minimal manual scanning intervention",
        "Platform becomes a genuine competitive moat",
      ],
      cons: [
        "Highest capital investment of the three options",
        "Complex multi-technology integration and maintenance",
        "Requires significant depot infrastructure changes",
        "18–36 month implementation timeline",
      ],
      timeframe: "18–36 months",
      investment: "Very High",
      impact: "Maximum",
      risk: "Medium–High",
      kpis: [
        "End-to-end tracking coverage percentage",
        "Depot processing automation rate",
        "Damage claim reduction",
        "Time-to-visibility from depot intake",
      ],
    },
  ],

  implementationRoadmap: {
    title: "Implementation Roadmap",
    phases: [
      {
        phase: "Phase 1",
        title: "Foundation",
        timeframe: "Months 1–6",
        color: "#22c55e",
        actions: [
          "Pilot magnetic GPS tags on 500 high-value shipments",
          "Build consumer tracking portal (web + mobile)",
          "Integrate with 3 anchor retailer clients",
          "Establish baseline KPIs",
        ],
      },
      {
        phase: "Phase 2",
        title: "Intelligence",
        timeframe: "Months 7–18",
        color: "#3b82f6",
        actions: [
          "Deploy automated exception detection engine",
          "Launch proactive notification system (SMS + email)",
          "Build retailer analytics dashboard",
          "Expand GPS tag deployment to all tracked-service parcels",
        ],
      },
      {
        phase: "Phase 3",
        title: "Platform",
        timeframe: "Months 19–36",
        color: "#a78bfa",
        actions: [
          "RFID integration at key depot intake points",
          "Computer vision pilot for damage detection",
          "IoT condition monitoring for premium service tier",
          "Full hybrid architecture operational",
        ],
      },
    ],
  },
};
