export const recommendationsContent = {
  title: "Strategic Recommendations",
  subtitle: "Five paths forward. One clear winner.",
  intro: "The evidence from the market, technology, and competitor analysis points to a clear strategic direction. These five recommendations are presented in priority order — with the first representing Ascent's highest-value, lowest-risk opportunity for immediate competitive differentiation.",

  summaryStats: [
    { label: "Recommendations", value: "5" },
    { label: "Implementation Phases", value: "3" },
    { label: "Total Timeline", value: "36 months" },
    { label: "Est. Investment Range", value: "£280k–£950k" },
  ],

  verdict: {
    headline: "The Strategic Verdict",
    body: "Ascent should lead with Magnetic GPS Tags as the core differentiator — it requires no infrastructure overhaul, delivers immediate parcel-level tracking, and occupies a capability gap that neither Royal Mail nor Detrack currently fills. The Automated System amplifies this advantage at scale. The White-Label Retailer Portal locks in revenue. Predictive ETAs win consumer loyalty. The Hybrid Architecture is the long-term moat.",
  },

  recommendations: [
    {
      id: "magnetic-gps",
      rank: 1,
      badge: "Recommended",
      badgeColor: "green",
      title: "Magnetic GPS Parcel Tracking",
      subtitle: "The fastest path to genuine differentiation",
      icon: "🧲",
      color: "#22c55e",
      description: "Deploy magnetic GPS tags on high-value and tracked parcels, providing real-time location data via cellular networks — no vehicle modification required. This immediately closes the biggest gap in the market: the absence of live, parcel-level tracking.",
      strategic_rationale: "Magnetic GPS is the only technology that delivers live parcel-level tracking without requiring infrastructure investment or carrier cooperation. It's retrofit-ready, scalable from day one, and directly addresses the consumer's top demand: knowing exactly where their parcel is, right now.",
      competitive_edge: "Royal Mail's tracking is event-based — it only updates at scan points, leaving hours-long blind spots. Detrack is a driver app, not a hardware solution. Magnetic GPS gives Ascent something neither can offer: continuous live location on the parcel itself, independent of any third party.",
      roi_estimate: "£40–80k saved annually per 10,000 parcels through theft reduction and dispute avoidance. At scale, tracking premium pricing of £1.50–3.00 per parcel creates a direct revenue stream.",
      pros: [
        "No infrastructure required — attach and track immediately",
        "Works on any carrier or vehicle type",
        "Real-time consumer-facing tracking maps",
        "Directly reduces theft and misdelivery disputes",
        "Scales from 1 to 1 million parcels without system changes",
      ],
      cons: [
        "Per-unit cost (£8–15 per tag) needs to be absorbed or passed on",
        "Battery lifecycle management required at scale",
        "Cellular data costs as ongoing OPEX (~£0.50/parcel/month)",
      ],
      implementation_steps: [
        "Source and test 3 GPS tag suppliers — compare battery life, form factor, cellular coverage",
        "Pilot with 500 high-value shipments across 3 courier partners over 8 weeks",
        "Build consumer tracking portal (web + iOS/Android PWA) with live map view",
        "Set up tag return/recharge logistics process and depot workflow",
        "Integrate tracking data feed into retailer dashboards via REST API",
        "Evaluate pilot KPIs and set rollout threshold (target: <0.3% loss rate, >80% consumer engagement)",
      ],
      timeframe: "0–6 months",
      investment: "Medium",
      impact: "Very High",
      risk: "Low",
      kpis: [
        { label: "Theft incidents per 1,000 deliveries", target: "< 0.5", unit: "incidents" },
        { label: "Customer satisfaction (tracking)", target: "> 4.5 / 5", unit: "score" },
        { label: "Dispute resolution time", target: "< 24 hours", unit: "hours" },
        { label: "Consumer tracking engagement", target: "> 75%", unit: "of recipients" },
      ],
    },
    {
      id: "automated-system",
      rank: 2,
      badge: "Conditional",
      badgeColor: "blue",
      title: "Automated Tracking & Exception System",
      subtitle: "Intelligence at scale — once the foundation is built",
      icon: "⚙️",
      color: "#3b82f6",
      description: "Build an automated exception management platform that detects delays, misrouting, and delivery failures in real-time, triggering proactive customer and retailer notifications before a complaint is raised.",
      strategic_rationale: "The data shows that 68% of consumers experienced delivery issues — but most only find out when the parcel doesn't arrive. An automated exception system transforms reactive customer service into proactive communication, dramatically improving satisfaction scores with minimal incremental cost once the tracking infrastructure is in place.",
      competitive_edge: "Royal Mail's customer service is reactive and phone-heavy, averaging 48+ hours to resolve exceptions. Detrack notifies drivers but not customers. An automated exception engine means Ascent contacts the customer before they even know there's a problem — a fundamental shift in the service experience no direct competitor currently offers.",
      roi_estimate: "Industry benchmark: automated proactive notifications reduce inbound complaint volume by 40–60%, cutting customer service headcount requirements by 2–4 FTE at 50,000 parcels/month. SLA-linked contracts can command a 15–25% pricing premium.",
      pros: [
        "Transforms customer service from reactive to proactive",
        "Reduces inbound complaint volume by 40–60% (industry benchmark)",
        "Provides retailers with real-time operational intelligence",
        "Enables SLA-based performance contracts with automatic compensation triggers",
        "Creates a data moat — insights competitors can't access",
      ],
      cons: [
        "Requires GPS/IoT tracking infrastructure as prerequisite (Rec #1)",
        "Platform integration complexity with retailer systems (3–6 month effort)",
        "Requires customer communication strategy, templates, and opt-in compliance (GDPR)",
      ],
      implementation_steps: [
        "Define exception taxonomy: delay thresholds, misroute triggers, failed-delivery criteria",
        "Build rules engine that reads GPS telemetry and flags anomalies in real-time",
        "Develop notification service: SMS (Twilio), email, and in-app push for consumer portal",
        "Build retailer-facing exception dashboard with drill-down per shipment",
        "Implement SLA contract framework with automated breach detection and credit triggering",
        "A/B test notification timing and tone — measure open rates, complaint deflection rate",
        "Launch retailer API: webhook-based exception feeds for enterprise integration",
      ],
      timeframe: "6–18 months",
      investment: "High",
      impact: "High",
      risk: "Medium",
      kpis: [
        { label: "Proactive notification rate", target: "> 90%", unit: "of exceptions" },
        { label: "Inbound complaint reduction", target: "> 45%", unit: "vs baseline" },
        { label: "Retailer NPS score", target: "> 60", unit: "NPS" },
        { label: "SLA breach rate", target: "< 2%", unit: "of shipments" },
        { label: "Exception detection latency", target: "< 15 min", unit: "from event" },
      ],
    },
    {
      id: "retailer-portal",
      rank: 3,
      badge: "High Value",
      badgeColor: "blue",
      title: "White-Label Retailer Tracking Portal",
      subtitle: "Turn tracking into a retention and revenue tool for your clients",
      icon: "🏪",
      color: "#06b6d4",
      description: "Offer retailers a fully branded, white-label tracking portal that embeds into their own website and post-purchase emails. Consumers see the retailer's brand — not Ascent's — but Ascent powers the experience and captures the data.",
      strategic_rationale: "Retailers spend thousands on post-purchase experience platforms (Narvar, Aftership) that cost £500–2,000/month per retailer. Ascent can offer an equivalent or superior product at a lower price, bundled with actual live tracking data no third-party tool can access. This creates high switching costs — once a retailer is live on the portal, churning means rebuilding their entire post-purchase flow.",
      competitive_edge: "Narvar and Aftership are pure software — they pull carrier tracking data and repackage it. They have no hardware layer and no real-time GPS. Ascent's portal would be the only white-label solution backed by live parcel-level data, giving retailers visibility that third-party tools fundamentally cannot provide.",
      roi_estimate: "SaaS pricing of £300–800/month per retailer client generates £180k–960k ARR at 50 clients. High-margin recurring revenue with near-zero marginal cost per additional retailer.",
      pros: [
        "Creates recurring SaaS revenue on top of logistics fees",
        "Deep retailer lock-in — high switching cost once integrated",
        "Retailer brand stays front-and-centre, increasing adoption likelihood",
        "Consumer tracking data improves Ascent's ML models over time",
        "Positions Ascent as a technology partner, not just a carrier",
      ],
      cons: [
        "Requires reliable underlying tracking data (dependency on Rec #1)",
        "White-label customisation adds UI/UX development overhead",
        "Onboarding support required per retailer (3–10 days per client)",
      ],
      implementation_steps: [
        "Define white-label feature set: branded tracking page, email templates, shipment timeline UI",
        "Build theming system: logo, colour scheme, domain CNAME support per retailer",
        "Develop retailer self-serve onboarding flow and API key management",
        "Create post-purchase email trigger integration (Klaviyo, Mailchimp, Shopify)",
        "Build retailer analytics dashboard: delivery performance, consumer engagement rates",
        "Price and package: tiered SaaS plans (Starter/Growth/Enterprise)",
      ],
      timeframe: "6–12 months",
      investment: "Medium",
      impact: "High",
      risk: "Low",
      kpis: [
        { label: "Retailer clients on portal", target: "> 25 in Year 1", unit: "clients" },
        { label: "Monthly recurring revenue (portal)", target: "> £15k MRR", unit: "by month 12" },
        { label: "Retailer churn rate", target: "< 5%", unit: "annual" },
        { label: "Consumer portal engagement", target: "> 65%", unit: "of recipients" },
      ],
    },
    {
      id: "predictive-eta",
      rank: 4,
      badge: "Differentiator",
      badgeColor: "purple",
      title: "Predictive Delivery Windows (AI ETAs)",
      subtitle: "Tell customers when their parcel will arrive — before it leaves the depot",
      icon: "🔮",
      color: "#8b5cf6",
      description: "Use machine learning trained on historical delivery telemetry, route data, and weather/traffic APIs to generate confident delivery window predictions — displayed as a 2-hour slot rather than a vague 'by end of day' estimate.",
      strategic_rationale: "WISMO (Where Is My Order) calls account for up to 40% of all e-commerce customer service volume. The root cause is almost always uncertainty — customers don't know when to be home, when to chase, or when to worry. A narrow, accurate delivery window eliminates this anxiety entirely and transforms the delivery experience without changing the physical operation.",
      competitive_edge: "Royal Mail's tracking shows status labels ('In Transit', 'Out for Delivery') with no time prediction. Detrack shows driver location but only on the day. Ascent can offer a 2-hour predicted window 24 hours in advance — a capability that Amazon Prime has trained consumers to expect, but that no independent carrier in the UK currently delivers.",
      roi_estimate: "Reducing WISMO contacts by 35% at 50,000 parcels/month saves approximately £25–40k/year in customer service costs. Premium 'timed delivery' service tier can command £2–4 surcharge per parcel.",
      pros: [
        "Directly addresses #1 consumer complaint: uncertainty about delivery time",
        "Reduces WISMO customer service contacts by 30–40%",
        "Enables premium 'Timed Delivery' service tier with surcharge",
        "Model improves automatically as more delivery data is collected",
        "Differentiates Ascent in B2C retailer pitches — tangible consumer benefit",
      ],
      cons: [
        "Requires 6–12 months of GPS telemetry data to train accurately",
        "Accuracy degrades in edge cases (rural routes, adverse weather, new drivers)",
        "Prediction failures damage trust more than no prediction at all",
      ],
      implementation_steps: [
        "Instrument GPS tags to capture full route telemetry: stops, dwell time, speed patterns",
        "Build historical delivery dataset: route, time of day, parcel count, weather, season",
        "Train gradient boosting model (XGBoost/LightGBM) predicting delivery time by postcode zone",
        "Set confidence threshold: only show predicted window if model confidence > 80%",
        "A/B test prediction display: 2-hour window vs 4-hour window vs time-of-day band",
        "Monitor prediction accuracy weekly; retrain model monthly on new data",
        "Launch 'Precision Delivery' premium tier with guaranteed 2-hour window SLA",
      ],
      timeframe: "12–24 months",
      investment: "Medium",
      impact: "High",
      risk: "Medium",
      kpis: [
        { label: "ETA prediction accuracy", target: "> 85%", unit: "within window" },
        { label: "WISMO contact reduction", target: "> 35%", unit: "vs baseline" },
        { label: "Premium tier adoption", target: "> 20%", unit: "of tracked shipments" },
        { label: "Consumer satisfaction (delivery certainty)", target: "> 4.6 / 5", unit: "score" },
      ],
    },
    {
      id: "hybrid",
      rank: 5,
      badge: "Long-Term",
      badgeColor: "purple",
      title: "Hybrid Tracking Architecture",
      subtitle: "The long-term vision — technology working in concert",
      icon: "🔗",
      color: "#a78bfa",
      description: "Combine GPS, RFID, IoT sensors, and computer vision into a unified tracking platform that provides continuous, multi-source location and condition data from depot intake to doorstep delivery.",
      strategic_rationale: "No single technology solves every tracking challenge. GPS excels in transit but struggles indoors. RFID is perfect for depot bulk scanning but has no range outdoors. Computer vision automates damage detection but is depot-bound. A hybrid architecture plays each technology to its strengths across the full parcel journey.",
      competitive_edge: "No UK independent carrier operates a hybrid tracking architecture at this level. Royal Mail relies on barcode scans at fixed points. DPD's Predict is GPS-on-driver, not GPS-on-parcel. A fully instrumented depot-to-door hybrid system would represent a genuine 3–5 year competitive moat that cannot be quickly replicated.",
      roi_estimate: "Full hybrid architecture supports a premium 'Condition Guarantee' product — live damage detection, tamper alerts, temperature monitoring for pharmaceuticals and perishables. This opens high-margin B2B verticals (pharma, electronics, luxury) worth £500k–2M+ ARR.",
      pros: [
        "Eliminates all tracking blind spots — full depot-to-door continuity",
        "Each technology reinforces the others' weaknesses",
        "Condition monitoring for high-value and fragile goods",
        "Maximum automation — minimal manual scanning intervention",
        "Platform becomes a genuine competitive moat",
      ],
      cons: [
        "Highest capital investment of the five options (£400k–600k+)",
        "Complex multi-technology integration and maintenance overhead",
        "Requires significant depot infrastructure changes and staff retraining",
        "18–36 month implementation timeline with high execution risk",
      ],
      implementation_steps: [
        "Complete Phase 1 GPS rollout and validate data pipeline reliability",
        "RFID pilot: gate readers at 2 depot intake points, measure scan accuracy vs barcode",
        "Computer vision pilot: camera-based damage detection on intake conveyor at 1 depot",
        "IoT sensor integration: temperature/humidity/shock for premium parcel tier",
        "Build unified data fusion layer: single shipment record ingesting GPS + RFID + CV events",
        "Launch 'Condition Guarantee' premium product for pharma and electronics verticals",
        "Gradual depot rollout: 1 depot fully hybrid, then expand to network",
      ],
      timeframe: "18–36 months",
      investment: "Very High",
      impact: "Maximum",
      risk: "Medium–High",
      kpis: [
        { label: "End-to-end tracking coverage", target: "> 99%", unit: "of journey" },
        { label: "Depot processing automation", target: "> 85%", unit: "no manual scan" },
        { label: "Damage claim reduction", target: "> 50%", unit: "vs baseline" },
        { label: "Time-to-visibility from depot intake", target: "< 2 min", unit: "minutes" },
        { label: "Premium vertical ARR", target: "> £500k", unit: "by Year 3" },
      ],
    },
  ],

  decisionMatrix: {
    title: "Decision Matrix",
    subtitle: "All five recommendations scored across key dimensions (1–5 scale)",
    criteria: ["Impact", "Speed", "Cost Efficiency", "Competitive Moat", "Execution Risk"],
    rows: [
      { id: "magnetic-gps",    label: "Magnetic GPS",         color: "#22c55e", scores: [5, 5, 4, 4, 5] },
      { id: "automated-system",label: "Automated Exceptions", color: "#3b82f6", scores: [4, 3, 5, 4, 3] },
      { id: "retailer-portal", label: "Retailer Portal",      color: "#06b6d4", scores: [4, 4, 5, 5, 4] },
      { id: "predictive-eta",  label: "Predictive ETAs",      color: "#8b5cf6", scores: [4, 3, 4, 4, 3] },
      { id: "hybrid",          label: "Hybrid Architecture",  color: "#a78bfa", scores: [5, 1, 2, 5, 2] },
    ],
  },

  implementationRoadmap: {
    title: "Implementation Roadmap",
    phases: [
      {
        phase: "Phase 1",
        title: "Foundation",
        timeframe: "Months 1–6",
        color: "#22c55e",
        actions: [
          "Source and evaluate GPS tag suppliers (battery, cost, coverage)",
          "Pilot magnetic GPS on 500 high-value shipments across 3 couriers",
          "Build consumer tracking portal (web + PWA) with live map",
          "Establish tag return and recharge workflow at depot",
          "Integrate with 3 anchor retailer clients via API",
          "Establish baseline KPIs: loss rate, CSAT, dispute volume",
          "Begin collecting route telemetry data for future ETA model",
        ],
      },
      {
        phase: "Phase 2",
        title: "Intelligence & Revenue",
        timeframe: "Months 7–18",
        color: "#3b82f6",
        actions: [
          "Deploy automated exception detection engine on GPS data stream",
          "Launch proactive notification system (SMS + email + in-app)",
          "Build retailer analytics dashboard with SLA breach tracking",
          "Expand GPS tag deployment to all tracked-service parcels",
          "Launch white-label retailer portal with CNAME and branding support",
          "Onboard first 10 retailers to white-label portal",
          "Begin ETA model training on 6 months of telemetry data",
          "Publish retailer API for enterprise system integrations",
        ],
      },
      {
        phase: "Phase 3",
        title: "Platform & Moat",
        timeframe: "Months 19–36",
        color: "#a78bfa",
        actions: [
          "Launch AI predictive delivery windows (2-hour slots) for consumer portal",
          "Release 'Precision Delivery' premium tier with window SLA guarantee",
          "RFID integration at key depot intake points (2 depots)",
          "Computer vision pilot for automated damage detection",
          "IoT condition monitoring for pharma and electronics tier",
          "Build unified data fusion layer across all tracking technologies",
          "Launch 'Condition Guarantee' product for high-value verticals",
          "Scale white-label portal to 25+ retailer clients",
        ],
      },
    ],
  },
};
