export const technologyContent = {
  title: "Technology Landscape",
  subtitle: "Six technologies. One question: which combination wins?",
  intro: "The parcel tracking industry is undergoing a quiet revolution. Six distinct technologies are competing — each with different cost profiles, accuracy levels, and operational trade-offs. Understanding their strengths and limitations is the first step to building the right system.",

  currentState: {
    title: "The Current State of Tracking",
    points: [
      { label: "Standard barcode scanning", description: "Static checkpoints only — no live location between scans", type: "limitation" },
      { label: "Basic GPS on some vehicles", description: "Vehicle-level tracking, not parcel-level", type: "limitation" },
      { label: "Manual proof of delivery", description: "Signature pads and handwritten notes — error-prone and dispute-heavy", type: "limitation" },
      { label: "No real-time consumer visibility", description: "Customers receive timestamps, not live maps", type: "limitation" },
    ],
    summary: "Most carriers today offer checkpoint-based tracking: a parcel is scanned at depot entry, depot exit, and delivery attempt. Everything in between is a black box. This is precisely where theft, misdelivery, and disputes occur.",
  },

  technologies: [
    {
      id: "gps",
      name: "GPS Tracking",
      icon: "🛰️",
      shortDesc: "Real-time location via satellite",
      description: "GPS provides continuous real-time location data, enabling live tracking maps that consumers and retailers increasingly expect. Modern GPS trackers have reached a price point where parcel-level attachment is feasible at scale.",
      cost: "Medium",
      costScore: 3,
      accuracy: "High",
      accuracyScore: 5,
      range: "Global",
      rangeScore: 5,
      automationLevel: "High",
      automationScore: 4,
      powerRequirement: "Medium",
      indoorPerformance: "Poor",
      bestFor: "Long-haul and last-mile vehicle tracking",
      limitations: "Battery drain, GPS dead zones in urban canyons",
      rating: 4,
      color: "#38bdf8",
    },
    {
      id: "rfid",
      name: "RFID",
      icon: "📡",
      shortDesc: "Radio frequency identification",
      description: "RFID enables bulk scanning of multiple parcels simultaneously without line-of-sight. Passive tags are cheap enough for single-use, while active tags offer extended read ranges for depot operations.",
      cost: "Low–Medium",
      costScore: 4,
      accuracy: "Medium",
      accuracyScore: 3,
      range: "Short (passive: <1m, active: <100m)",
      rangeScore: 2,
      automationLevel: "Very High",
      automationScore: 5,
      powerRequirement: "None (passive)",
      indoorPerformance: "Excellent",
      bestFor: "Depot sorting, bulk intake scanning",
      limitations: "Limited range, interference from metal/liquid",
      rating: 3,
      color: "#a78bfa",
    },
    {
      id: "iot",
      name: "IoT Sensors",
      icon: "📟",
      shortDesc: "Connected sensors for condition + location",
      description: "IoT devices combine GPS, temperature, humidity, shock, and tilt sensors into a single unit. Essential for high-value or fragile goods — they provide tamper alerts, environmental condition logs, and chain-of-custody proof.",
      cost: "High",
      costScore: 2,
      accuracy: "Very High",
      accuracyScore: 5,
      range: "Global (via cellular/LoRaWAN)",
      rangeScore: 5,
      automationLevel: "Very High",
      automationScore: 5,
      powerRequirement: "Medium–High",
      indoorPerformance: "Good",
      bestFor: "High-value goods, fragile items, pharmaceuticals",
      limitations: "Cost prohibitive for standard parcels",
      rating: 4,
      color: "#34d399",
    },
    {
      id: "barcode",
      name: "Barcode / QR Scanning",
      icon: "📊",
      shortDesc: "Industry-standard checkpoint scanning",
      description: "Barcodes remain the backbone of parcel tracking — cheap, universal, and reliable for creating checkpoint-based event logs. QR codes add consumer-facing utility with self-service tracking portals.",
      cost: "Very Low",
      costScore: 5,
      accuracy: "High (at scan points)",
      accuracyScore: 3,
      range: "Point-of-scan only",
      rangeScore: 1,
      automationLevel: "Medium",
      automationScore: 3,
      powerRequirement: "None",
      indoorPerformance: "Excellent",
      bestFor: "Depot check-in/out, universal compatibility",
      limitations: "Zero live tracking between scan points",
      rating: 2,
      color: "#fbbf24",
    },
    {
      id: "magnetic",
      name: "Magnetic GPS Tags",
      icon: "🧲",
      shortDesc: "Attachable GPS with no infrastructure needed",
      description: "Magnetic GPS tags attach to any surface and transmit location data via cellular networks — no special infrastructure required. They represent a significant innovation for retrofit deployments, enabling parcel-level tracking without modifying existing vehicle fleets.",
      cost: "Medium",
      costScore: 3,
      accuracy: "High",
      accuracyScore: 4,
      range: "Global (cellular)",
      rangeScore: 5,
      automationLevel: "High",
      automationScore: 4,
      powerRequirement: "Low (long battery life)",
      indoorPerformance: "Medium",
      bestFor: "Retrofit fleets, high-value parcel tracking, last-mile",
      limitations: "Per-unit cellular data cost, battery replacement",
      rating: 5,
      color: "#f472b6",
      highlighted: true,
    },
    {
      id: "computer-vision",
      name: "Computer Vision / AI",
      icon: "👁️",
      shortDesc: "Camera-based automated parcel identification",
      description: "Computer vision enables automated parcel identification, damage detection at intake, and AI-powered routing. Combined with camera networks at depots, it creates a continuous, automated chain-of-custody record without requiring any tag on the parcel.",
      cost: "High (infrastructure)",
      costScore: 2,
      accuracy: "Very High",
      accuracyScore: 5,
      range: "Depot-based",
      rangeScore: 2,
      automationLevel: "Maximum",
      automationScore: 5,
      powerRequirement: "High (server infrastructure)",
      indoorPerformance: "Excellent",
      bestFor: "Depot automation, damage claims reduction, throughput",
      limitations: "High upfront cost, depot-only coverage",
      rating: 4,
      color: "#fb923c",
    },
  ],

  comparisonMatrix: {
    headers: ["Technology", "Cost", "Live Tracking", "Indoor", "Automation", "Range", "Overall"],
    scoreLabels: { 1: "Poor", 2: "Limited", 3: "Moderate", 4: "Good", 5: "Excellent" },
  },
};
